### ISSUE TITLE
OpenLevelUp: Empty area colour

### ISSUE THREAD

**Issue by k1wiosm** [PanierAvide/panieravide.github.io#10]
Currently it seems that when there is an empty area in a building it is coloured depending on the category of the building itself. I think it would make more sense to have it always the same colour.

Examples: [1](http://github.pavie.info/openlevelup/?lat=42.800449769580524&lon=-1.636771112680435&zoom=19&tiles=0&level=3&transcend=1&unrendered=0&buildings=0&photos=0&notes=0), [2](http://github.pavie.info/openlevelup/?lat=42.79953857768991&lon=-1.6356982290744781&zoom=19&tiles=0&level=2&transcend=1&unrendered=0&buildings=0&photos=0&notes=0), [3](http://github.pavie.info/openlevelup/?lat=42.78395472606333&lon=-1.6322126984596252&zoom=18&tiles=0&level=0&transcend=1&unrendered=0&buildings=0&photos=0&notes=0)

**Comment by PanierAvide** [comment]
Well, all the building have the same colour (#D4CACA), but they are most of the time covered with other objects. Walk-able areas are coloured in very light grey (#EEEEEE), and rooms in light grey (#E0E0E0). So the colour depends of the tagged objects, they don't have the same signification (as I understand the wiki) :
* Building (without room/area) : not accessible
* Area : large area without walls (walls can be added with indoor=wall)
* Room : smaller area with walls (no need of indoor=wall)

**Comment by k1wiosm** [comment]
Yes, I know about that. I don't think I made myself clear enough, sorry. I'll try again.

The colour that you are using for __Building (without room/area) : not accessible__ is not always #D4CACA.

On [1](http://github.pavie.info/openlevelup/?lat=42.800449769580524&lon=-1.636771112680435&zoom=19&tiles=0&level=3&transcend=1&unrendered=0&buildings=0&photos=0&notes=0) the building is [tagged](http://www.openstreetmap.org/way/90645911) with `building=university`, and you are correctly using #D4CACA. 
On [2](http://github.pavie.info/openlevelup/?lat=42.79953857768991&lon=-1.6356982290744781&zoom=19&tiles=0&level=2&transcend=1&unrendered=0&buildings=0&photos=0&notes=0) the building is [tagged](http://www.openstreetmap.org/way/90645941) with `building=university + amenity=library`, and you are using #FFDDC2.
On [3](http://github.pavie.info/openlevelup/?lat=42.78395472606333&lon=-1.6322126984596252&zoom=18&tiles=0&level=0&transcend=1&unrendered=0&buildings=0&photos=0&notes=0) the building is [tagged](http://www.openstreetmap.org/way/233897157) with `building=yes + shop=mall`, and you are using #EEEEEE.

**Comment by PanierAvide** [comment]
Oh I see, this is caused by rules applied when `amenity=library` or `shop=mall` are defined. So you think that buildings with such tags should be rendered like a default one ? It makes sense, but I don't know if it's good to hide differences between buildings.

**Comment by k1wiosm** [comment]
When you are using an indoor map what you want to see is what is inside the building. I think that it doesn't make sense to use the colour associated to the building itself to colour empty areas of the building.

If you don't want to lose that information, maybe (or maybe not, i don't know) you could use a side menu (similar to the rooms one that you have) to show the buildings that are shown and their properties.

**Comment by PanierAvide** [comment]
I think this is the good approach, I will do it ;)
