### ISSUE TITLE
display entrances

### ISSUE THREAD

**Issue by GuillaumeAllegre** [PanierAvide/panieravide.github.io#11]
Thanks for OpenLevelUp, this is a very promising software.

I suggest to add a rendering (maybe a little dot) for entrances (*maybe* styled upon value : main, yes, service, exit, emergency).
And maybe, if not too difficult, to have different styles on inner and outer entrances.

**Comment by GuillaumeAllegre** [comment]
and, please can you tell me how I can add a label (enhancement here) ?

**Comment by PanierAvide** [comment]
Thank you :) Entrances are already rendered (`entrance=*` or `door=*` tags) but only at highest zoom levels (20 and more). And labels can only be added by me, that's why ;) Let me know if you want more details or have any suggestion about this.

**Comment by GuillaumeAllegre** [comment]
J'ai l'impression qu'il y a un bug alors (ici à Grenoble)
http://github.pavie.info/openlevelup/?lat=45.183507&lon=5.703247&z=20&t=1&lvl=0&tcd=1&urd=1&bdg=0&pic=1&nte=1
Cette salle apparaît bien : 
http://www.openstreetmap.org/way/322443010
Mais ses deux entrées non 
http://www.openstreetmap.org/node/3798064641
http://www.openstreetmap.org/node/3798064637

**Comment by k1wiosm** [comment]
Je pense que vous devez ajouter un tag level=*

**Comment by PanierAvide** [comment]
C'est ça, il faut au moins un tag de niveau sur l'objet (`level` ou `repeat_on` ou inclus dans une relation `type=level`).
