### ISSUE TITLE
Better UX: select latest time-segment immediately

### ISSUE THREAD

**Issue by d1g** [PanierAvide/panieravide.github.io#13]
Background: you have to click at the element in order to move time-segment.

Default precision is quite low and you will make 15m errors sooner or later.

Right now you have to click latest (erroneous) segment in order to correct your imperfection.

Solution is to: 1. lower fidelity 2. make it tunable 3. select latest segment so user can decide if it was mistake or not

**Comment by PanierAvide** [comment]
Do these comments apply to time intervals already added or when creating a new one ?

**Comment by d1g** [comment]
@PanierAvide Hm, I think we need this only when there completely new interval with *error in the duration* so you have to correct it somehow. There also assumption that most users want to correct their errors right after they spot them.


PS. These comments may apply if users start to introduce errors in duration during process of moves. I think this will occur less often, or at least in current setup/size of control elements.

**Comment by PanierAvide** [comment]
So if I understand, the issue is that the last created time interval isn't selected at start, making impossible to resize it directly without clicking on it a first time, that's right ?

**Comment by d1g** [comment]
From user perspective, correct. 

But important that there no hints "please click segment to resize it". Some users are used to how resizing functions in their OS. In most systems you don't have to click at element/window in order to resize it.

You just hover mouse over control element and drag mouse.

**Comment by PanierAvide** [comment]
This is solved, please reopen if needed ;)
