### ISSUE TITLE
YoHours: Edit field does not update the weektable "all year".

### ISSUE THREAD

**Issue by ypid** [PanierAvide/panieravide.github.io#14]
Am I wrong or did this work already?

##### Steps to reproduce:

1. Open http://github.pavie.info/yohours/
2. Enter `Mo 04:00-08:00; PH off`

##### Expected result

All year time table gets an entry for `Mo 04:00-08:00`. An PH tab gets added with an empty time table.

##### Actual result

All year time table has no entries. An PH tab gets added with an empty time table.

PS: Checked it with `Mo 01:30-10:30; PH 08:00-14:00` and PH is handled correctly.

**Comment by PanierAvide** [comment]
Fixed, it was due to the start of week being by default sunday in moment.js, and day display is based on first day of the week, so the interval was shown on calendar, but at the next week (so hidden). Thanks for reporting ;)

**Comment by ypid** [comment]
Thanks for the quick fix :+1:
