### ISSUE TITLE
Support the simple POI mapping spec too

### ISSUE THREAD

**Issue by simonpoole** [PanierAvide/panieravide.github.io#15]
Thank you for your nice tool. When we were devising the SIT spec one of our goals was to add a very simple first step for mappers that don't want to or can^t start adding floor plans. I believe this is important because it supports step wise refinement one of the underlying principles of OSM.

It would be nice if you could support it too, see https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging#Simple_POI_mapping besides a level tag on the object it requires min_level and max_level tags on the building outline.

**Comment by PanierAvide** [comment]
It is normally already supported (see `Feature` class in `model.js`, those tags are used). So building using level-related tags are shown on correct levels. Can you provide an example if it doesn't work somewhere ?

**Comment by simonpoole** [comment]
Hmm seems as if it does actually work (just re-tested) and that I was simply expecting the update to soon. Which overpass instance are you using?

**Comment by PanierAvide** [comment]
This one http://www.overpass-api.de/api/ it has in fact a delay of a few minutes.

**Comment by simonpoole** [comment]
Hmm, when I initially tested I specifically checked if that instance had the added data. Lets put it down to Gremlins for now.

**Comment by simonpoole** [comment]
I suspect what is confusing me is that you don't actually get a visual indication that there is something there see http://github.pavie.info/openlevelup/?lat=47.423217&lon=8.368492&z=16&t=0 with the result that you probably wont zoom in far enough.

**Comment by PanierAvide** [comment]
The cluster view indicates areas with precise indoor features (indoor=* or buildingpart=* + level=*), this is done this way to have something relatively accurate and a fast response from Overpass API. That's why most of the tags are ignored on low zoom.
