### ISSUE TITLE
YoHours: UX preserve text cursor position after each validation

### ISSUE THREAD

**Issue by d1g** [PanierAvide/panieravide.github.io#19]
Right now, cursor will reset to the end after new character <s>until there valid string</s> (actually it will reset cursor even if validation succeeds). User have to reposition cursor multiple times until he gets his OH string.

**Comment by PanierAvide** [comment]
I'm not having this issue of cursor being moved to the end while editing (using Firefox), what browser are you using ?

**Comment by d1g** [comment]
@PanierAvide,
* Google Chrome 48.0.2564.0 canary
* Firefox 44.0a2

Both without plugins in private mode, but I'm not sure what exactly causes this behaviour.

**Comment by PanierAvide** [comment]
I can reproduce it in Chromium 46, I will fix it.
