### ISSUE TITLE
YoHours. Use opening_hours.js

### ISSUE THREAD

**Issue by ypid** [PanierAvide/panieravide.github.io#2]
Really nice project … I was not aware of it and just read about it on the mailing list.
Please consider adding it to the wiki and I will probably also add a reference from the [evaluation tool](http://openingh.openstreetmap.de/evaluation_tool/). I have added YoHours to [the projects which use opening_hours.js](https://github.com/ypid/opening_hours.js#used-by-other-projects). Looking thought the code, it seems that you are not using opening_hours.js right now but parse the syntax yourself. I don’t think that this is a good idea …

**Comment by PanierAvide** [comment]
Thanks ;) I was using it before, but it doesn't fit to what I wanted to do, the API is more "specific-time" oriented, while I reconstruct here a general calendar. I didn't found a way to use to make it return general time intervals such as a typical monday during august.

**Comment by ypid** [comment]
Should be possible. You can give opening_hours.js a part of the oh value and have it return the times for the week. When they are changed by the user, there is probably no easy way to feed that back into opening_hours.js but you have written code to handle that. The thing you could have reused is probably the tokenize function and work with the `tokens` array as [documented](https://github.com/ypid/opening_hours.js/tree/master/docs) because parsing the syntax with all it’s specialties is very hard.

Either way. You have created something which works quite good and I have not looks too deep at the code yet to wisely recommend something. One thing you could do is to check with opening_hours.js if a value is valid even if YoHours can not parse it and maybe offer a link to the evaluation tool.

I am thinking about a check in the evaluation tool if the value is supported by YoHours and refer to it if it is. Probably the easiest way is to include via git submodules the YoHours model and try, if it can parse the value. Would you like to write a patch for that?

BTW: Nice code layout. I know my HTML is really messy because I did not clean it up yet. Yours looks well designed. Well done :+1: 
Also nice license choice. Thats the one thing which bugs me a bit about opening_hours.js that everybody could make changes and keep them closed-source.

PS: YoHours is not very prominent at the very bottom :) I think it should go a bit higher (next to the evaluation tool) but that can probably be done in the rewrite: https://wiki.openstreetmap.org/wiki/User:M!dgard/Key:opening_hours

**Comment by PanierAvide** [comment]
Yes I saw that the `tokens` array does the job well, but as YoHours doesn't support the full syntax I thought it would be easier to implement a simple parser than to copy and adapt parts of opening_hours.js. Couldn't it be possible to your library to return in a simpler array the result of the parsing ? For example, an array of objects, where each object describe a given rule, with the date selector and time range (or comment or something else depending of the kind of rule). That would be more high-level and less prone to errors than making everyone analysing the raw tokens array by himself.

Nevertheless, I like the idea to check if the syntax is valid with your library and display a link if YoHours can't read it. I will add it as soon as possible ;)

That would be great :) I can make it simpler to check if it's valid, something like a `YoHoursValidator` object with a `isValid(oh)` method returning a boolean value. That way you will have just to include the `model.js` file and call this where you need.

Thank you :) This license was proposed by another mapper on the talk-fr mailing list, and that fits perfectly. Sharing changes made to open-source projects is important in my opinion, makes software better for everyone ;)

**Comment by PanierAvide** [comment]
Job done. See [Integration](https://github.com/PanierAvide/panieravide.github.io/tree/master/yohours#integration) for how to use it in an external component, and [an example](http://github.pavie.info/yohours/?oh=24/7;%20week%2001%20Su%2001:00-10:30%20||%20%22on%20appointment%22) of value showing an alert linking to your web tool ;)

**Comment by ypid** [comment]
Well done :+1:

**Comment by PanierAvide** [comment]
The syntax check doesn't work without user location or when holidays are missing in opening_hours.js when PH or SH is defined in opening_hours value. See ypid/opening_hours.js#100.

**Comment by ypid** [comment]
Do you want to translate this to France?

    "refer to yohorus": 'This value can also be parsed by YoHours which is a simple editor for the opening_hours syntax. If you don’t need advanced features of the syntax, <a href=\"__href__\">give it a try</a>.'

**Comment by PanierAvide** [comment]
You made a typo at "yohours" in "refer to yohorus".
```
"refer to yohours": 'Cette valeur peut également s'afficher dans YoHours, un éditeur simple d'horaires d'ouverture. Si vous n'utilisez pas les fonctionnalités avancées de la syntaxe, <a href=\"__href__\">vous pouvez l'essayer ici</a>.'
```

**Comment by ypid** [comment]
Thanks.

**Comment by PanierAvide** [comment]
Thank you for the integration ;)

**Comment by PanierAvide** [comment]
Integration fully works, closing the issue. Thanks for the changes made in opening_hours.js ;)
