### ISSUE TITLE
YoHours: endtime is not displayed unless interval is bigger than 1h

### ISSUE THREAD

**Issue by d1g** [PanierAvide/panieravide.github.io#20]
Context: http://github.pavie.info/yohours/?oh=Mo%2004:00-04:30,05:00-06:15;%20Tu%2004:00-05:00;%20We%2004:00-04:15
Browser: Google Chrome 48.0.2564.0 canary
Browser: Firefox 44.0a2

Not sure if it is bug or a feature, but we may want to display labels at intervals more consistently (i.e. endtime should be displayed with starttime)

**Comment by PanierAvide** [comment]
It's not a feature, I will fix it ;)
