### ISSUE TITLE
OpenLevelUp: Supporting conveying=yes

### ISSUE THREAD

**Issue by k1wiosm** [PanierAvide/panieravide.github.io#22]
`indoor=room + stairs=yes + conveying=yes` is the [Simple Indoor Tagging](https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging#Modelling_connections_between_different_levels) way of tagging escalators.

It would be nice if you could support it.

**Comment by PanierAvide** [comment]
I will add this conveying stairs rendering ;)
