### ISSUE TITLE
OpenLevelUp: No rendering of incline ways

### ISSUE THREAD

**Issue by gsn01** [PanierAvide/panieravide.github.io#27]
The incline ways (in french : "rampes") are not rendered. It would be easier to represent ways through levels, for example inside stations
http://github.pavie.info/openlevelup/?lat=48.520697&lon=2.255563&z=19&t=0&lvl=0&tcd=1&urd=0&bdg=0&pic=0&nte=0

**Comment by PanierAvide** [comment]
Which object (OSM ID) are you referring to ? Do you mean that ways with `incline` tag may be rendered differently than other ways ?

**Comment by PanierAvide** [comment]
No response for a while, if you want the issue to be fixed or have some new comments, please create an issue in the new repository : https://git.framasoft.org/PanierAvide/OpenLevelUp/issues
