### ISSUE TITLE
YoHours: questionable "; Th 00:00"

### ISSUE THREAD

**Issue by d1g** [PanierAvide/panieravide.github.io#28]
Context http://github.pavie.info/yohours/?oh=We%2000:00-23:45

Steps to reproduce: drag bottom slider to the end (24:00)
Observed: http://github.pavie.info/yohours/?oh=We%2000:00-24:00;%20Th%2000:00
Expected: http://github.pavie.info/yohours/?oh=We%2000:00-24:00

Chrome 49.0.2619.3 canary
Aurora 45.0a2 (2015-12-17)

**Comment by d1g** [comment]
Tested again, I get this behaviour every time.

Similarly, if you drag top slider from state http://github.pavie.info/yohours/?oh=We%2000:15-00:00
you will get same "We 00:00-24:00; Th 00:00"

**Comment by PanierAvide** [comment]
Thanks for reporting ;)
