### ISSUE TITLE
Extend an interval not working

### ISSUE THREAD

**Issue by tuxayo** [PanierAvide/panieravide.github.io#3]
On Firefox 40 and Chromium 44
When dragging the "=" sign on intervals extremities
The cusor becomes a forbidden sign and the inverval doesn't change
No JS errors

**Comment by HolgerJeromin** [comment]
Extending a Monday time to the right would be nice, too. 
So I have for example Monday 8-18 a clock and drag it to the right and have mo - fr 8-18 
In my tests this did not worked. I am not sure if this is a bug or not implemented.

**Comment by PanierAvide** [comment]
Extending time intervals from top or bottom is implemented but stopped working. Extending from right or left isn't implemented (the main library Fullcalendar doesn't do it natively, I will have to implement it). This is planned to be done ;)

**Comment by PanierAvide** [comment]
This is weird, extending time intervals from top/bottom works under Chromium 45 and Firefox 40 on Windows 7, and Firefox 38 under Manjaro Linux. It wasn't working yesterday under Firefox 40 on Arch Linux.

**Comment by PanierAvide** [comment]
Can't reproduce it any more anywhere, maybe it was cache related. I'm closing this issue, don't hesitate to re-open it with more elements if necessary ;)

**Comment by HolgerJeromin** [comment]
Thanks

**Comment by tuxayo** [comment]
It works! Strange!
