### ISSUE TITLE
OpenLevelUp: Make it easier to browse the map

### ISSUE THREAD

**Issue by keunes** [PanierAvide/panieravide.github.io#30]
Currently, after each move on the map, data needs to get loaded and that takes quite some time. Exploring a university campus that way can get pretty annoying. Maybe one way to solve it would be to let the user know data downloading is happening in the background, but not disable moving (or zooming) the map.

**Comment by PanierAvide** [comment]
That's a good point, I will work on this ;)

**Comment by PanierAvide** [comment]
Moved issue to Framasoft : https://git.framasoft.org/PanierAvide/OpenLevelUp/issues/4
