### ISSUE TITLE
OpenLevelUp: Bug positionnement pictos

### ISSUE THREAD

**Issue by overflorian** [PanierAvide/panieravide.github.io#31]
Hello,
Il y a des pictos qui ne s'affichent pas du tout au centre de leur polygone sur les quais de cette gare : http://openlevelup.net/?lat=48.794890&lon=2.134888&z=20&t=0&lvl=-1&tcd=1&urd=0&bdg=0&pic=0&nte=0&ilv=0
![capture](https://cloud.githubusercontent.com/assets/11553211/13357034/c00390c6-dca8-11e5-9cf4-4e783f871a46.PNG)
Une idée du problème ?
Merci

**Comment by PanierAvide** [comment]
En fait les pictos sont placés au centroïde du polygone, c'est à dire à la coordonnée moyenne de tous les points qui le composent. Et dans certains cas celui-ci est hors du polygone. Vu la courbure du quai, c'est ce qui se passe ici. À moins de changer la méthode de calcul, il n'y a pas grand chose à faire.

**Comment by overflorian** [comment]
à toi de voir si tu as le courage de chercher une solution ;)

**Comment by PanierAvide** [comment]
Je vais regarder ça d'ici peu ;) Le ticket est déplacé sur Framasoft : https://git.framasoft.org/PanierAvide/OpenLevelUp/issues/5
