### ISSUE TITLE
YoHours: A non-overlapping rectangular selection

### ISSUE THREAD

**Issue by d1g** [PanierAvide/panieravide.github.io#32]
JOSM plugin uses this by default: [yohours ATM](http://i.imgur.com/YwxMi87.png) and [JOSM](http://i.imgur.com/fe6LoMe.png)

[AFAIK, overlaps happen infrequently IRL (if you account 1/8 values are 24/7 in data)](http://openingh.openstreetmap.de/stats/). Note a 7-23 rectangle in data.

You would expect [24/7 shifts](https://en.wikipedia.org/wiki/Shift_work#Industries) more frequently than 24/2 + 5 days of a normal service. Only some restaurants and nightclubs do this, for other less profitable cases, they simply prefer 5 days (in shifts) + 2 short weekends.

**Comment by PanierAvide** [comment]
The solution to this problem would be to allow right/left extending, see #4
