### ISSUE TITLE
Deploy Subresource Integrity

### ISSUE THREAD

**Issue by ypid** [PanierAvide/panieravide.github.io#34]
YoHours as an example uses: https://code.jquery.com/jquery-1.10.2.js
I think we had a discussion about this once. I now agree that common files can be downloaded from CDNs (ideally with fall back) for normal projects but only with Subresource Integrity deployed. Ideally, you would self host http://projets.pavie.info before solving this issue and upgrade to https :wink:

Refs: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by PanierAvide** [comment]
Thanks, added to YoHours and OpenRandomMap, as other projects now uses NPM packages.
