### ISSUE TITLE
YoHours : start from nowhere

### ISSUE THREAD

**Issue by Mziserman** [PanierAvide/panieravide.github.io#36]
https://github.com/PanierAvide/panieravide.github.io/blob/master/yohours/js/model.js#L540
at the end of the ligne there is start.day > 1. I'm pretty sure this should be o._start.day > 1.

**Comment by PanierAvide** [comment]
Thanks for reporting, you're right. As YoHours repository has moved, the fix was made there: https://framagit.org/PanierAvide/YoHours/commit/1959b889823daa97c512ab2a965d6d3cc1842fd9
