### ISSUE TITLE
YoHours: wrong range displayed for times beginning with 08 and 09

### ISSUE THREAD

**Issue by HolgerJeromin** [PanierAvide/panieravide.github.io#5]
This trivial example is buggy: `Mo 09:00-22:00`
But `Mo 08:15-09:00` and especially `Mo 08:00-09:00` (visually equal to 24/7) is fun, too :-)

**Comment by PanierAvide** [comment]
Works here, what's your browser ? Can you try to clear your cache and check again ?

**Comment by HolgerJeromin** [comment]
Opera 12 (last browser with the presto webengine). clearing the cache did not solve the issue

**Comment by PanierAvide** [comment]
Fixed, it was a weird behaviour of `parseInt()` function when base parameter is missing.

**Comment by HolgerJeromin** [comment]
yes, sure. This "feature" of parseInt ist quite surprising. :-)

Thanks for fixing it!
