### ISSUE TITLE
YoHours: mixing Weekdays and PH is buggy

### ISSUE THREAD

**Issue by HolgerJeromin** [PanierAvide/panieravide.github.io#6]
`Mo-Fr 12:00-14:00;Sa,Su,PH 12:00-16:00` kills the Weekend display. 
The result from `Mo-Sa,PH 12:00-16:00` is completely confusing.

**Comment by PanierAvide** [comment]
Thanks for reporting, I can reproduce it. I will check that ;)

**Comment by PanierAvide** [comment]
This bug is now fixed.
