### ISSUE TITLE
OpenLevelUp: Specific male & female toilet symbols

### ISSUE THREAD

**Issue by k1wiosm** [PanierAvide/panieravide.github.io#7]
You have specific male & female toilet symbols (https://github.com/PanierAvide/panieravide.github.io/blob/master/openlevelup/img/amenity_toilets_men.png, https://github.com/PanierAvide/panieravide.github.io/blob/master/openlevelup/img/amenity_toilets_women.png) but it seems that you are not using them. Or at least I am unable of figuring out what combination of key-values will show them. 
I am using `amenity=toilets + female=yes + indoor=room + level=2 + male=no` but the generic toilet symbol is used.

**Comment by PanierAvide** [comment]
You're right, the distinction isn't made on map for the while, I will do it soon ;)

**Comment by HolgerJeromin** [comment]
what about wheelchair toilet icon? :-)

**Comment by PanierAvide** [comment]
This will be done too :)

**Comment by PanierAvide** [comment]
Done in a3c4379aac0152934af3c2e500d4a91d729848a5, thanks for this enhancement ;)

**Comment by HolgerJeromin** [comment]
Thanks, found my wrong tag women instead of female with this change :-)

**Comment by k1wiosm** [comment]
#8
