### ISSUE TITLE
OpenLevelUp: Supporting stairs=yes

### ISSUE THREAD

**Issue by k1wiosm** [PanierAvide/panieravide.github.io#9]
The [Simple Indoor Tagging proposal](http://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging#Modelling_connections_between_different_levels) recommends using `indoor=room + stairs=yes` for mapping stairs inside a building.

It would be nice if you could support it.

**Comment by PanierAvide** [comment]
Done, thank you for the idea :)
